*** Auto Generated by TruePath Ultimate Version 1.0.0 ***

*** Settings ***
*** Documentation of the NDTV web application Main page objects ***

*** Variables ***

${ndtv_page_title}       xpath://a[@href='https://www.ndtv.com']
${ndtv_page_submenu}       xpath://a[@id='h_sub_menu']
${weather_page_url}     https://social.ndtv.com/static/Weather/report/?pfrom=home-topsubnavigation
${cityPinClass}     message_holder_header
${cityPinText}      Pin your City
${searchBox_ID}     id=searchBox







